resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-script
    branch: main
  check_every: 5s 


jobs:
- name: run-helloworld
  plan:
  - get: my-git-repo
    trigger: true
  - task: execute-helloworld
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 'latest'
      inputs:
      - name: my-git-repo
      run:
        path: sh
        args:
        - -exc
        - |
          pwd
          cd my-git-repo
          ls -la
          cat test



